-- ----------------------------
-- Sequence structure for expiration_options_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."expiration_options_id_seq";
CREATE SEQUENCE "public"."expiration_options_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
ALTER SEQUENCE "public"."expiration_options_id_seq" OWNER TO "postgres";
-- ----------------------------
-- Sequence structure for link_access_logs_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."link_access_logs_id_seq";
CREATE SEQUENCE "public"."link_access_logs_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
ALTER SEQUENCE "public"."link_access_logs_id_seq" OWNER TO "postgres";
-- ----------------------------
-- Sequence structure for links_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."links_id_seq";
CREATE SEQUENCE "public"."links_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
ALTER SEQUENCE "public"."links_id_seq" OWNER TO "postgres";
-- ----------------------------
-- Sequence structure for user_oauth_providers_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."user_oauth_providers_id_seq";
CREATE SEQUENCE "public"."user_oauth_providers_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
ALTER SEQUENCE "public"."user_oauth_providers_id_seq" OWNER TO "postgres";
-- ----------------------------
-- Sequence structure for users_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."users_id_seq";
CREATE SEQUENCE "public"."users_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
ALTER SEQUENCE "public"."users_id_seq" OWNER TO "postgres";
-- ----------------------------
-- Table structure for expiration_options
-- ----------------------------
DROP TABLE IF EXISTS "public"."expiration_options";
CREATE TABLE "public"."expiration_options" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1
  ),
  "name" text COLLATE "pg_catalog"."default" NOT NULL,
  "days" int4,
  "is_permanent" bool DEFAULT false
);
ALTER TABLE "public"."expiration_options" OWNER TO "postgres";
-- ----------------------------
-- Table structure for link_access_logs
-- ----------------------------
DROP TABLE IF EXISTS "public"."link_access_logs";
CREATE TABLE "public"."link_access_logs" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1
  ),
  "link_id" int8 NOT NULL,
  "accessed_at" timestamptz(6) NOT NULL DEFAULT now(),
  "ip_address" text COLLATE "pg_catalog"."default",
  "user_agent" text COLLATE "pg_catalog"."default",
  "referrer" text COLLATE "pg_catalog"."default"
);
ALTER TABLE "public"."link_access_logs" OWNER TO "postgres";
-- ----------------------------
-- Table structure for links
-- ----------------------------
DROP TABLE IF EXISTS "public"."links";
CREATE TABLE "public"."links" (
  "link" text COLLATE "pg_catalog"."default" NOT NULL,
  "short" text COLLATE "pg_catalog"."default" NOT NULL,
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1
  ),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "user_id" int8,
  "expires_at" timestamptz(6),
  "is_public" bool DEFAULT false,
  "access_count" int8 DEFAULT 0
);
ALTER TABLE "public"."links" OWNER TO "postgres";
COMMENT ON TABLE "public"."links" IS '短链接表';
-- ----------------------------
-- Table structure for user_oauth_providers
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_oauth_providers";
CREATE TABLE "public"."user_oauth_providers" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1
  ),
  "user_id" int8 NOT NULL,
  "provider" text COLLATE "pg_catalog"."default" NOT NULL,
  "provider_user_id" text COLLATE "pg_catalog"."default" NOT NULL,
  "created_at" timestamptz(6) NOT NULL DEFAULT now()
);
ALTER TABLE "public"."user_oauth_providers" OWNER TO "postgres";
-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1
  ),
  "username" text COLLATE "pg_catalog"."default",
  "email" text COLLATE "pg_catalog"."default",
  "password_hash" text COLLATE "pg_catalog"."default",
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "last_login" timestamptz(6)
);
ALTER TABLE "public"."users" OWNER TO "postgres";
-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."expiration_options_id_seq" OWNED BY "public"."expiration_options"."id";
SELECT setval('"public"."expiration_options_id_seq"', 5, true);
-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."link_access_logs_id_seq" OWNED BY "public"."link_access_logs"."id";
SELECT setval('"public"."link_access_logs_id_seq"', 1, false);
-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."links_id_seq" OWNED BY "public"."links"."id";
SELECT setval('"public"."links_id_seq"', 139, true);
-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."user_oauth_providers_id_seq" OWNED BY "public"."user_oauth_providers"."id";
SELECT setval(
    '"public"."user_oauth_providers_id_seq"',
    1,
    false
  );
-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."users_id_seq" OWNED BY "public"."users"."id";
SELECT setval('"public"."users_id_seq"', 1, false);
-- ----------------------------
-- Primary Key structure for table expiration_options
-- ----------------------------
ALTER TABLE "public"."expiration_options"
ADD CONSTRAINT "expiration_options_pkey" PRIMARY KEY ("id");
-- ----------------------------
-- Indexes structure for table link_access_logs
-- ----------------------------
CREATE INDEX "idx_link_access_logs_accessed_at" ON "public"."link_access_logs" USING btree (
  "accessed_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);
CREATE INDEX "idx_link_access_logs_link_id" ON "public"."link_access_logs" USING btree (
  "link_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
-- ----------------------------
-- Primary Key structure for table link_access_logs
-- ----------------------------
ALTER TABLE "public"."link_access_logs"
ADD CONSTRAINT "link_access_logs_pkey" PRIMARY KEY ("id");
-- ----------------------------
-- Indexes structure for table links
-- ----------------------------
CREATE INDEX "idx_links_expires_at" ON "public"."links" USING btree (
  "expires_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);
CREATE INDEX "idx_links_short" ON "public"."links" USING btree (
  "short" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_links_user_id" ON "public"."links" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
-- ----------------------------
-- Primary Key structure for table links
-- ----------------------------
ALTER TABLE "public"."links"
ADD CONSTRAINT "links_pkey" PRIMARY KEY ("id");
-- ----------------------------
-- Indexes structure for table user_oauth_providers
-- ----------------------------
CREATE INDEX "idx_user_oauth_providers_user_id" ON "public"."user_oauth_providers" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
-- ----------------------------
-- Uniques structure for table user_oauth_providers
-- ----------------------------
ALTER TABLE "public"."user_oauth_providers"
ADD CONSTRAINT "user_oauth_providers_unique" UNIQUE ("provider", "provider_user_id");
-- ----------------------------
-- Primary Key structure for table user_oauth_providers
-- ----------------------------
ALTER TABLE "public"."user_oauth_providers"
ADD CONSTRAINT "user_oauth_providers_pkey" PRIMARY KEY ("id");
-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "public"."users"
ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
-- ----------------------------
-- Foreign Keys structure for table link_access_logs
-- ----------------------------
ALTER TABLE "public"."link_access_logs"
ADD CONSTRAINT "link_access_logs_link_id_fkey" FOREIGN KEY ("link_id") REFERENCES "public"."links" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
-- ----------------------------
-- Foreign Keys structure for table links
-- ----------------------------
ALTER TABLE "public"."links"
ADD CONSTRAINT "links_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE
SET NULL ON UPDATE NO ACTION;
-- ----------------------------
-- Foreign Keys structure for table user_oauth_providers
-- ----------------------------
ALTER TABLE "public"."user_oauth_providers"
ADD CONSTRAINT "user_oauth_providers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;